name: Deploy Pipeline

on:
  push:
    branches: [ main ]

# Permissions required for OIDC (Role Assumption)
permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: us-east-1
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_env: "dev"
      TF_VAR_domain_name: "aws-workshops.com"
      IAM_ROLE_ARN: arn:aws:iam::637423443220:role/GitHubActionRole
      TF_STATE_KEY: "healthtech/dev/terraform.tfstate"

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (remote state)
        run: |
          terraform init -upgrade -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
            -backend-config="encrypt=true"
        # FIXED: Changed from ./infra to ./terraform
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # FIXED: Changed from ./infra to ./terraform
        working-directory: ./terraform
